name: Update Rules List

on:
  schedule:
    - cron: '0 0 * * *'    # 0ç‚¹æ‰§è¡Œä¸€æ¬¡ï¼ˆUTCï¼‰
  workflow_dispatch:       # æ‰‹åŠ¨è§¦å‘
  push:                    # ä»£ç æäº¤è§¦å‘

jobs:
  update-ip-list:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§¾ Checkout repository
        uses: actions/checkout@v3

      - name: ğŸ Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: ğŸ“¦ Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: ğŸš€ Run clash_rules_merged.py
        run: python clash_rules_merged.py

      - name: âœ… Commit and push
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

          
          # æ£€æŸ¥æ˜¯å¦æœ‰ä»»ä½•å˜æ›´
          if git diff --quiet; then
            echo "No changes detected, skipping commit."
          else
            git add .
            git commit -m "Automatic update by ${{ github.actor }}"
            git push
          fi
